// This test is automatically generated by @matanuska/test-generator.
// See ./packages/test-generator/README.md for more details.

import { describe, test, expect } from 'vitest';

import { FILENAME } from './helpers/files';
import { parseProgram } from './helpers/parser';

describe('operator precedence', () => {
  test('16 - 15 / 14 - 13 > 12 >= not 11 >= 10 = 9 and 8 or - 7 == 6 + 5 * 4 <> 3 != 2 < 1', () => {
    const [ast, warning] = parseProgram(
      `10 16 - 15 / 14 - 13 > 12 >= not 11 >= 10 = 9 and 8 or - 7 == 6 + 5 * 4 <> 3 != 2 < 1`,
      FILENAME,
    );

    expect((ast.lines[0].instructions[0] as any).expression).toMatchSnapshot();
    expect(warning).toMatchSnapshot();
  });
});
