// This test is automatically generated by @matanuska/test-generator.
// See ./packages/test-generator/README.md for more details.

import { describe, test, expect } from 'vitest';

import { FILENAME } from './helpers/files';
import { parseProgram } from './helpers/parser';

const EXPR =
  '15 = - 14 + 13 * 12 or 11 / 10 < 9 != 8 <> 7 == 6 > 5 - 4 and 3 >= 2 >= not 1';

describe('operator precedence', () => {
  test(EXPR, () => {
    const [ast, warning] = parseProgram(`10 ${EXPR}`, FILENAME);

    expect((ast.lines[0].instructions[0] as any).expression).toMatchSnapshot();
    expect(warning).toMatchSnapshot();
  });
});
