export enum Type {
  Integer = 'integer',
  Real = 'real',
  Boolean = 'boolean',
  String = 'string',
  Exception = 'Exception',
  Nil = 'nil',
  Undef = 'undef',
  Input = 'input',
  Program = 'program',
  Function = 'function',
  Any = 'any',
  Unknown = 'unknown',
  Invalid = 'invalid',
}
