name: QA
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  qa:
    name: Run QA checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/Iron", "latest"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Matanuska
        run: npm install
      - name: Build Matanuska
        run: dotenv -f ./test.env -- npm run 'build:templates' && tsc -p tsconfig.build.json
      - name: Test
        run: dotenv -f ./test.env -- ./node_modules/.bin/tap --reporter=base --allow-incomplete-coverage ./test
      - name: Lint
        run: './node_modules/.bin/prettier --list-different "**.ts" && ./node_modules/.bin/eslint --fix "**.ts"'
      - name: Shell check
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'
